// <auto-generated />
using System;
using CameraInspector.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CameraInspector.Persistence.Migrations
{
    [DbContext(typeof(CameraInspectorDbContext))]
    partial class CameraInspectorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CameraInspector.Persistence.Entities.CameraCredentialEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CameraId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CredentialRef")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastVerifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CameraId")
                        .IsUnique();

                    b.HasIndex("CredentialRef")
                        .IsUnique();

                    b.ToTable("CameraCredentials");
                });

            modelBuilder.Entity("CameraInspector.Persistence.Entities.CameraEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Firmware")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hostname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Info")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastTest")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mac")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ip");

                    b.HasIndex("Mac");

                    b.ToTable("Cameras");
                });

            modelBuilder.Entity("CameraInspector.Persistence.Entities.CameraEventEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CameraId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.ToTable("CameraEvents");
                });

            modelBuilder.Entity("CameraInspector.Persistence.Entities.CameraInterfaceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CameraId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.ToTable("CameraInterfaces");
                });

            modelBuilder.Entity("CameraInspector.Persistence.Entities.CameraTestEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CameraId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResponseTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("TestDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TestName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TestType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CameraId");

                    b.ToTable("CameraTests");
                });

            modelBuilder.Entity("CameraInspector.Persistence.Entities.CameraCredentialEntity", b =>
                {
                    b.HasOne("CameraInspector.Persistence.Entities.CameraEntity", null)
                        .WithOne("Credential")
                        .HasForeignKey("CameraInspector.Persistence.Entities.CameraCredentialEntity", "CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CameraInspector.Persistence.Entities.CameraEventEntity", b =>
                {
                    b.HasOne("CameraInspector.Persistence.Entities.CameraEntity", null)
                        .WithMany("Events")
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CameraInspector.Persistence.Entities.CameraInterfaceEntity", b =>
                {
                    b.HasOne("CameraInspector.Persistence.Entities.CameraEntity", null)
                        .WithMany("Interfaces")
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CameraInspector.Persistence.Entities.CameraTestEntity", b =>
                {
                    b.HasOne("CameraInspector.Persistence.Entities.CameraEntity", null)
                        .WithMany("Tests")
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CameraInspector.Persistence.Entities.CameraEntity", b =>
                {
                    b.Navigation("Credential");
                    b.Navigation("Events");
                    b.Navigation("Interfaces");
                    b.Navigation("Tests");
                });
#pragma warning restore 612, 618
        }
    }
}
